services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: backend-pref
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  backend:
    build: .
    container_name: backend-pref
    ports:
    - "3000:3000" 
    environment:
      DATABASE_URL: "postgresql://admin:admin@pg:5432/backend-pref"
      URL_REDIS: "redis://redis:6379"
    depends_on:
      - pg